/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model;


import it.giacomobergami.jOOQ.model.tables.CurrentDeptEmp;
import it.giacomobergami.jOOQ.model.tables.Departments;
import it.giacomobergami.jOOQ.model.tables.DeptEmp;
import it.giacomobergami.jOOQ.model.tables.DeptEmpLatestDate;
import it.giacomobergami.jOOQ.model.tables.DeptManager;
import it.giacomobergami.jOOQ.model.tables.Employees;
import it.giacomobergami.jOOQ.model.tables.Salaries;
import it.giacomobergami.jOOQ.model.tables.Titles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in employees
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * VIEW
     */
    public static final CurrentDeptEmp CURRENT_DEPT_EMP = it.giacomobergami.jOOQ.model.tables.CurrentDeptEmp.CURRENT_DEPT_EMP;

    /**
     * The table <code>employees.departments</code>.
     */
    public static final Departments DEPARTMENTS = it.giacomobergami.jOOQ.model.tables.Departments.DEPARTMENTS;

    /**
     * The table <code>employees.dept_emp</code>.
     */
    public static final DeptEmp DEPT_EMP = it.giacomobergami.jOOQ.model.tables.DeptEmp.DEPT_EMP;

    /**
     * VIEW
     */
    public static final DeptEmpLatestDate DEPT_EMP_LATEST_DATE = it.giacomobergami.jOOQ.model.tables.DeptEmpLatestDate.DEPT_EMP_LATEST_DATE;

    /**
     * The table <code>employees.dept_manager</code>.
     */
    public static final DeptManager DEPT_MANAGER = it.giacomobergami.jOOQ.model.tables.DeptManager.DEPT_MANAGER;

    /**
     * The table <code>employees.employees</code>.
     */
    public static final Employees EMPLOYEES_ = it.giacomobergami.jOOQ.model.tables.Employees.EMPLOYEES_;

    /**
     * The table <code>employees.salaries</code>.
     */
    public static final Salaries SALARIES = it.giacomobergami.jOOQ.model.tables.Salaries.SALARIES;

    /**
     * The table <code>employees.titles</code>.
     */
    public static final Titles TITLES = it.giacomobergami.jOOQ.model.tables.Titles.TITLES;
}
