/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.daos;


import it.giacomobergami.jOOQ.model.tables.DeptManager;
import it.giacomobergami.jOOQ.model.tables.records.DeptManagerRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeptManagerDao extends DAOImpl<DeptManagerRecord, it.giacomobergami.jOOQ.model.tables.pojos.DeptManager, Record2<Integer, String>> {

    /**
     * Create a new DeptManagerDao without any configuration
     */
    public DeptManagerDao() {
        super(DeptManager.DEPT_MANAGER, it.giacomobergami.jOOQ.model.tables.pojos.DeptManager.class);
    }

    /**
     * Create a new DeptManagerDao with an attached configuration
     */
    public DeptManagerDao(Configuration configuration) {
        super(DeptManager.DEPT_MANAGER, it.giacomobergami.jOOQ.model.tables.pojos.DeptManager.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, String> getId(it.giacomobergami.jOOQ.model.tables.pojos.DeptManager object) {
        return compositeKeyRecord(object.getEmpNo(), object.getDeptNo());
    }

    /**
     * Fetch records that have <code>emp_no IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.DeptManager> fetchByEmpNo(Integer... values) {
        return fetch(DeptManager.DEPT_MANAGER.EMP_NO, values);
    }

    /**
     * Fetch records that have <code>dept_no IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.DeptManager> fetchByDeptNo(String... values) {
        return fetch(DeptManager.DEPT_MANAGER.DEPT_NO, values);
    }

    /**
     * Fetch records that have <code>from_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.DeptManager> fetchByFromDate(Date... values) {
        return fetch(DeptManager.DEPT_MANAGER.FROM_DATE, values);
    }

    /**
     * Fetch records that have <code>to_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.DeptManager> fetchByToDate(Date... values) {
        return fetch(DeptManager.DEPT_MANAGER.TO_DATE, values);
    }
}
