/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.daos;


import it.giacomobergami.jOOQ.model.enums.EmployeesGender;
import it.giacomobergami.jOOQ.model.tables.Employees;
import it.giacomobergami.jOOQ.model.tables.records.EmployeesRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesDao extends DAOImpl<EmployeesRecord, it.giacomobergami.jOOQ.model.tables.pojos.Employees, Integer> {

    /**
     * Create a new EmployeesDao without any configuration
     */
    public EmployeesDao() {
        super(Employees.EMPLOYEES_, it.giacomobergami.jOOQ.model.tables.pojos.Employees.class);
    }

    /**
     * Create a new EmployeesDao with an attached configuration
     */
    public EmployeesDao(Configuration configuration) {
        super(Employees.EMPLOYEES_, it.giacomobergami.jOOQ.model.tables.pojos.Employees.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(it.giacomobergami.jOOQ.model.tables.pojos.Employees object) {
        return object.getEmpNo();
    }

    /**
     * Fetch records that have <code>emp_no IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByEmpNo(Integer... values) {
        return fetch(Employees.EMPLOYEES_.EMP_NO, values);
    }

    /**
     * Fetch a unique record that has <code>emp_no = value</code>
     */
    public it.giacomobergami.jOOQ.model.tables.pojos.Employees fetchOneByEmpNo(Integer value) {
        return fetchOne(Employees.EMPLOYEES_.EMP_NO, value);
    }

    /**
     * Fetch records that have <code>birth_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByBirthDate(Date... values) {
        return fetch(Employees.EMPLOYEES_.BIRTH_DATE, values);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByFirstName(String... values) {
        return fetch(Employees.EMPLOYEES_.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByLastName(String... values) {
        return fetch(Employees.EMPLOYEES_.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByGender(EmployeesGender... values) {
        return fetch(Employees.EMPLOYEES_.GENDER, values);
    }

    /**
     * Fetch records that have <code>hire_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Employees> fetchByHireDate(Date... values) {
        return fetch(Employees.EMPLOYEES_.HIRE_DATE, values);
    }
}
