/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.daos;


import it.giacomobergami.jOOQ.model.tables.Salaries;
import it.giacomobergami.jOOQ.model.tables.records.SalariesRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalariesDao extends DAOImpl<SalariesRecord, it.giacomobergami.jOOQ.model.tables.pojos.Salaries, Record2<Integer, Date>> {

    /**
     * Create a new SalariesDao without any configuration
     */
    public SalariesDao() {
        super(Salaries.SALARIES, it.giacomobergami.jOOQ.model.tables.pojos.Salaries.class);
    }

    /**
     * Create a new SalariesDao with an attached configuration
     */
    public SalariesDao(Configuration configuration) {
        super(Salaries.SALARIES, it.giacomobergami.jOOQ.model.tables.pojos.Salaries.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Date> getId(it.giacomobergami.jOOQ.model.tables.pojos.Salaries object) {
        return compositeKeyRecord(object.getEmpNo(), object.getFromDate());
    }

    /**
     * Fetch records that have <code>emp_no IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Salaries> fetchByEmpNo(Integer... values) {
        return fetch(Salaries.SALARIES.EMP_NO, values);
    }

    /**
     * Fetch records that have <code>salary IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Salaries> fetchBySalary(Integer... values) {
        return fetch(Salaries.SALARIES.SALARY, values);
    }

    /**
     * Fetch records that have <code>from_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Salaries> fetchByFromDate(Date... values) {
        return fetch(Salaries.SALARIES.FROM_DATE, values);
    }

    /**
     * Fetch records that have <code>to_date IN (values)</code>
     */
    public List<it.giacomobergami.jOOQ.model.tables.pojos.Salaries> fetchByToDate(Date... values) {
        return fetch(Salaries.SALARIES.TO_DATE, values);
    }
}
