/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Departments implements Serializable {

    private static final long serialVersionUID = -95056592;

    private String deptNo;
    private String deptName;

    public Departments() {}

    public Departments(Departments value) {
        this.deptNo = value.deptNo;
        this.deptName = value.deptName;
    }

    public Departments(
        String deptNo,
        String deptName
    ) {
        this.deptNo = deptNo;
        this.deptName = deptName;
    }

    public String getDeptNo() {
        return this.deptNo;
    }

    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    public String getDeptName() {
        return this.deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Departments (");

        sb.append(deptNo);
        sb.append(", ").append(deptName);

        sb.append(")");
        return sb.toString();
    }
}
