/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.pojos;


import it.giacomobergami.jOOQ.model.enums.EmployeesGender;

import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees implements Serializable {

    private static final long serialVersionUID = 1661527462;

    private Integer         empNo;
    private Date            birthDate;
    private String          firstName;
    private String          lastName;
    private EmployeesGender gender;
    private Date            hireDate;

    public Employees() {}

    public Employees(Employees value) {
        this.empNo = value.empNo;
        this.birthDate = value.birthDate;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.gender = value.gender;
        this.hireDate = value.hireDate;
    }

    public Employees(
        Integer         empNo,
        Date            birthDate,
        String          firstName,
        String          lastName,
        EmployeesGender gender,
        Date            hireDate
    ) {
        this.empNo = empNo;
        this.birthDate = birthDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.hireDate = hireDate;
    }

    public Integer getEmpNo() {
        return this.empNo;
    }

    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public EmployeesGender getGender() {
        return this.gender;
    }

    public void setGender(EmployeesGender gender) {
        this.gender = gender;
    }

    public Date getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(empNo);
        sb.append(", ").append(birthDate);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(gender);
        sb.append(", ").append(hireDate);

        sb.append(")");
        return sb.toString();
    }
}
