/**
 * This class is generated by jOOQ
 */
package it.giacomobergami.jOOQ.model.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Titles implements Serializable {

    private static final long serialVersionUID = 965988748;

    private Integer empNo;
    private String  title;
    private Date    fromDate;
    private Date    toDate;

    public Titles() {}

    public Titles(Titles value) {
        this.empNo = value.empNo;
        this.title = value.title;
        this.fromDate = value.fromDate;
        this.toDate = value.toDate;
    }

    public Titles(
        Integer empNo,
        String  title,
        Date    fromDate,
        Date    toDate
    ) {
        this.empNo = empNo;
        this.title = title;
        this.fromDate = fromDate;
        this.toDate = toDate;
    }

    public Integer getEmpNo() {
        return this.empNo;
    }

    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Titles (");

        sb.append(empNo);
        sb.append(", ").append(title);
        sb.append(", ").append(fromDate);
        sb.append(", ").append(toDate);

        sb.append(")");
        return sb.toString();
    }
}
